# 1. Base image
FROM node:22.8

# 2. Working directory in the container
WORKDIR /app

# 3. Copy package.json and package-lock.json
COPY front/gsw-api/package*.json .

# 4. Install dependencies
RUN npm install

# 5. Copy the rest of the application code
COPY front/gsw-api/. .

# 6. Expose the port the app runs on (default for Node.js apps is 3000)
EXPOSE 3000

# 7. Command to run the application
CMD ["npm", "run", "dev:container"]